version: '3.8'

services:
  katone-license:
    container_name: katone-license
    image: katone-license:${LICENSE_SERVER_VERSION}
    environment:
      KIT_DATABASE_URL: "${DB_HOST}:${DB_PORT}/kit"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      KIT_SERVER_URL: "${LICENSE_SERVER_URL}"
      LICENSE_SERVER_URL: "${LICENSE_SERVER_URL}"

  katone-server:
    container_name: katone-server
    image: katone-server:${LICENSE_SERVER_VERSION}
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "${DB_HOST}:${DB_PORT}"
      QUARKUS_DATASOURCE_USERNAME: "${DB_USERNAME}"
      QUARKUS_DATASOURCE_PASSWORD: "${DB_PASSWORD}"

  katone-proxy:
    container_name: katone-proxy
    image: katone-proxy:${LICENSE_SERVER_VERSION}
    ports:
      - ${LICENSE_SERVER_PORT}:80
    volumes:
      - ./fix-ipv6.sh:/docker-entrypoint.d/25-fix-ipv6.sh
    depends_on:
      - katone-license
      - katone-server
